version: '3'

services:
  app:
    image: 'kecampcr/localizacion:v0.0.1'
    build:
      context: .
    container_name: app
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080
