INSERT INTO PROVINCIA (COD_PROVINCIA, NOM_PROVINCIA) VALUES(1, 'SAN JOSE');
INSERT INTO PROVINCIA (COD_PROVINCIA, NOM_PROVINCIA) VALUES(2, 'ALAJUELA');
INSERT INTO PROVINCIA (COD_PROVINCIA, NOM_PROVINCIA) VALUES(3, 'CARTAGO');
INSERT INTO PROVINCIA (COD_PROVINCIA, NOM_PROVINCIA) VALUES(4, 'HEREDIA');
INSERT INTO PROVINCIA (COD_PROVINCIA, NOM_PROVINCIA) VALUES(5, 'GUANACASTE');
INSERT INTO PROVINCIA (COD_PROVINCIA, NOM_PROVINCIA) VALUES(6, 'PUNTARENAS');
INSERT INTO PROVINCIA (COD_PROVINCIA, NOM_PROVINCIA) VALUES(7, 'LIMON');