apiVersion: v1
kind: ConfigMap
metadata:
  name: localizacion-cm
  namespace: localizacion-ns
data:
  # property-like keys; each key maps to a simple value
  STAGE: "QA"
  PARAM: "user-interface.properties"

  # file-like keys
  application.properties: |
    spring.application.name=CM-Microserv.Localizacion
    #Server port
    server.port=8080
    #CharsetEncoding
    spring.http.encoding.charset=UTF-8
    spring.http.encoding.enabled=true
    #Testing DS
    spring.datasource.url=jdbc:h2:mem:testdb
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=sa
    spring.datasource.password=password
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.sql.init.mode=embedded
    spring.jpa.defer-datasource-initialization=true
    info.app.name=@project.artifactId@
    info.app.description=@project.description@
    info.app.version=@project.version@
    info.app.encoding=@project.build.sourceEncoding@
    info.app.java.version=@java.version@
   
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true   